version: "3.8"

services:
  mongo_db:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data/db/mongo:/data/db
    ports:
      - 27017:27017

  postgres_db:
    container_name: postgres
    image: postgres
    restart: always
    hostname: postgres_fundoo
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
      - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES=ms_user,ms_note,ms_label
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 1
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass ${REDIS_PWD}
    restart: always
    volumes:
      - ./data/db/redis:/data
    environment:
      REDIS_PWD: ${REDIS_PWD}
    ports:
      - 6379:6379

  rabbitmq:
    container_name: rmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
    ports:
      - 15672:15672
      - 5672:5672

  app:
    container_name: fundoo
    image: fundoo_fastapi
    build: .
    volumes:
      - .:/app
    depends_on:
      - mongo_db
      - postgres_db
      - redis

  fundoo_user:
    container_name: user
    image: fundoo_fastapi
    command: bash -c "uvicorn main:user_app --proxy-headers --host 0.0.0.0 --port ${USER_PORT}"
    restart: always
    ports:
      - ${USER_PORT}:${USER_PORT}
    expose:
      - ${USER_PORT}
    depends_on:
      - app
      - postgres_db

  fundoo_note:
    container_name: notes
    image: fundoo_fastapi
    command: bash -c "uvicorn main:note_app --proxy-headers --host 0.0.0.0 --port ${NOTE_PORT}"
    restart: always
    ports:
      - ${NOTE_PORT}:${NOTE_PORT}
    expose:
      - ${NOTE_PORT}
    depends_on:
      - app
      - postgres_db

  fundoo_label:
    container_name: label
    image: fundoo_fastapi
    command: bash -c "uvicorn main:label_app --proxy-headers --host 0.0.0.0 --port ${LABEL_PORT}"
    restart: always
    ports:
      - ${LABEL_PORT}:${LABEL_PORT}
    expose:
      - ${LABEL_PORT}
    depends_on:
      - app
      - postgres_db

  celery_worker:
    container_name: celery_worker
    image: fundoo_fastapi
    command: bash -c "celery -A core.tasks.celery worker -l INFO --pool=solo --uid=0"
    restart: always
    environment:
      - C_FORCE_ROOT= true
      - CELERY_BROKER_URL=${CELERY_BROKER}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT}
    depends_on:
      - redis

  celery_beat:
    container_name: redbeat
    image: fundoo_fastapi
    command: bash -c "celery -A core.tasks.celery beat -l INFO"
    restart: always
    depends_on:
      - redis

  rabbit_consumer:
    container_name: consumer
    image: fundoo_fastapi
    command: bash -c "python3 core/rmq_consumer.py"
    restart: always
    depends_on:
      - rabbitmq
