"""init collaborator model

Revision ID: 4187ee22a261
Revises: db137dfed2da
Create Date: 2023-07-08 15:50:22.427921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4187ee22a261'
down_revision = 'db137dfed2da'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_ms_user() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ms_user() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ms_note() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborator_id'), 'collaborator', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade_ms_note() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaborator_id'), table_name='collaborator')
    op.drop_table('collaborator')
    # ### end Alembic commands ###


def upgrade_ms_label() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ms_label() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

