"""init labelCollaborator

Revision ID: 69033aacc48d
Revises: 631f853a299c
Create Date: 2023-07-11 12:05:23.536295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69033aacc48d'
down_revision = '631f853a299c'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_ms_user() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ms_user() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ms_note() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ms_note() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ms_label() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_notes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('label_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_notes_id'), 'label_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade_ms_label() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_notes_id'), table_name='label_notes')
    op.drop_table('label_notes')
    # ### end Alembic commands ###

